// Find broken internal `/0-1-0-preview/...` links across hand-authored MDX/MD docs.
// Skips:
//  - reference/api/*  (auto-generated by DocFX)
//  - source/*         (synced from engine repo)
//  - /th/ locale duplicates (English content is the source of truth)
//
// Prints lines as:  <source-file>:<line>:<lin>: <link>  ->  <reason>
//
// A link is "broken" if its `/0-1-0-preview/<section>/<path>/` does not match
// either an `index.mdx` in <section>/<path>/  or  a `<path>.mdx` in <section>/.

import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { resolve, relative } from 'node:path';

const root = resolve('src/content/docs/0-1-0-preview');
const englishRoot = root;

// 1) Build set of canonical page slugs we ship.
const slugs = new Set();
const sections = ['guide', 'tutorials', 'technology', 'migration', 'reference', 'contributing', 'source'];

function walk(dir, relPrefix = '') {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = resolve(dir, entry.name);
    const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      walk(abs, rel);
    } else if (/\.(md|mdx)$/i.test(entry.name)) {
      // Canonicalise to URL slug (matches Astro/Starlight's slug generation).
      let slug = rel
        .replace(/\\/g, '/')
        .replace(/\/index\.(md|mdx)$/i, '/')
        .replace(/\.(md|mdx)$/i, '/');
      // Astro lowercases and treats dots in filename as path separators
      // (DocFX-generated `Cephalon.Foo.Bar.md` → `cephalon-foo-bar/`).
      slug = slug
        .split('/')
        .map((segment) => segment.replace(/\./g, '-').toLowerCase())
        .join('/');
      if (!slug.endsWith('/')) slug += '/';
      slugs.add(`/0-1-0-preview/${slug}`);
    }
  }
}

for (const s of sections) {
  walk(resolve(englishRoot, s), s);
}
// Add section roots (so /0-1-0-preview/guide/ works if guide/index.mdx exists).
slugs.add('/0-1-0-preview/');

// About lives outside the version. Walk recursively — about/ has sub-directories.
function walkAbout(dir, relPrefix = '') {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = resolve(dir, entry.name);
    const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      walkAbout(abs, rel);
    } else if (/\.(md|mdx)$/i.test(entry.name)) {
      let slug = rel
        .replace(/\\/g, '/')
        .replace(/\/index\.(md|mdx)$/i, '/')
        .replace(/\.(md|mdx)$/i, '/');
      slug = slug
        .split('/')
        .map((segment) => segment.replace(/\./g, '-').toLowerCase())
        .join('/');
      if (!slug.endsWith('/')) slug += '/';
      slugs.add(`/about/${slug}`);
    }
  }
}
walkAbout(resolve('src/content/docs/about'));
slugs.add('/about/');

// 2) Scan hand-authored files for internal links.
const MD_LINK_RE = /\]\((\/(?:0-1-0-preview|about)\/[^)\s#"]*)(#[^)\s"]*)?\)/g;
const HREF_RE = /href=["'](\/(?:0-1-0-preview|about)\/[^"'#]*)(#[^"']*)?["']/g;

const broken = [];
// Scan EVERYTHING — including synced source/* and DocFX-generated api/*
// because users actually click links in those pages too. If a sync-imported
// page links to /reference/api/X and X doesn't exist, that's still broken
// from a visitor's POV.
const skipDirs = new Set();

function scan(file) {
  const text = readFileSync(file, 'utf8');
  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const matchAll = [
      ...line.matchAll(MD_LINK_RE),
      ...line.matchAll(HREF_RE),
    ];
    for (const m of matchAll) {
      let target = m[1];
      // Normalise: must end with /
      if (!target.endsWith('/')) target += '/';
      if (!slugs.has(target)) {
        broken.push({ file: relative(process.cwd(), file).replace(/\\/g, '/'), line: i + 1, target, raw: m[0] });
      }
    }
  }
}

function walkScan(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      if (skipDirs.has(entry.name)) continue;
      walkScan(abs);
    } else if (/\.(md|mdx)$/i.test(entry.name)) {
      scan(abs);
    }
  }
}

walkScan(englishRoot);
// Skip Thai locale (translation lag — fix English first)

// Group by target for triage.
const byTarget = new Map();
for (const b of broken) {
  if (!byTarget.has(b.target)) byTarget.set(b.target, []);
  byTarget.get(b.target).push(b);
}

const sortedTargets = [...byTarget.entries()].sort((a, b) => b[1].length - a[1].length);

console.log(`Found ${broken.length} broken link references to ${byTarget.size} unique targets.\n`);

for (const [target, refs] of sortedTargets) {
  console.log(`\x1b[33m${target}\x1b[0m  (${refs.length} reference${refs.length === 1 ? '' : 's'})`);
  for (const r of refs) {
    console.log(`   ${r.file}:${r.line}`);
  }
}

process.exit(broken.length > 0 ? 1 : 0);
